name: 'xcode-build-github-action'
description: 'This action will build with Xcode and output ipa.'
inputs:
  app-id:
    description: >
      Specify the App ID.

      ex) com.akiojin.Sample
    required: false
  workspace:
    description: 'Path to the workspace file'
    required: false
    default: ''
  project:
    description: 'Path to the project file'
    required: false
    default: ''
  output-directory:
    description: >
      The directory in which the ipa file should be stored in.
    required: true
  output-name:
    description: >
      Specifies the name of the ipa file to be output.
    required: false
    default: Build
  scheme:
    description: >
      The project's scheme.
      Defaults to 'Unity-iPhone'
    required: false
    default: 'Unity-iPhone'
  sdk:
    description: >
      The SDK that should be used for building the application.
      Defaults to 'iphoneos'
    required: false
    default: 'iphoneos'
  configuration:
    description: >
      The configuration to use when building the app.
      Specify 'Debug' or 'Release'.
      Defaults to 'Debug'
    required: false
    default: 'Debug'
  export-method:
    description: >
      Define the profile type,
      can be appstore, adhoc, development, enterprise, developer_id, mac_installer_distribution
    required: false
    default: 'development'
  include-bitcode:
    description: >
      Should the ipa file include bitcode?
      Defaults to false
    required: false
    default: false
  include-symbols:
    description: >
      Should the ipa file include symbols?
      Defaults to false
    required: false
    default: false
  team-id:
    description: >
      The ID of your Developer Portal team if you're in multiple teams.
    required: true
  provisioning-profile-name:
    description: >
      Specify the Name of the provisioning profile.
      If app-id is specified, this parameter must be specified.
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"